
package com.javaproject.examplecollect.wsdlclient.myhellowsdlfromserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWSDLModifyServer", targetNamespace = "http://abc.com/")
@XmlSeeAlso({
    //ObjectFactory.class
})
public interface HelloWSDLModifyServer {


    /**
     * 
     * @param myNum
     * @param myMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "myReturn", targetNamespace = "")
    @RequestWrapper(localName = "getMsg", targetNamespace = "http://abc.com/", className = "com.javaproject.examplecollect.wsdlclient.myhellowsdlfromserver.GetMsg")
    @ResponseWrapper(localName = "getMsgResponse", targetNamespace = "http://abc.com/", className = "com.javaproject.examplecollect.wsdlclient.myhellowsdlfromserver.GetMsgResponse")
    @Action(input = "http://abc.com/HelloWSDLModifyServer/getMsgRequest", output = "http://abc.com/HelloWSDLModifyServer/getMsgResponse")
    public String getMsg(
        @WebParam(name = "myMsg", targetNamespace = "")
        String myMsg,
        @WebParam(name = "myNum", targetNamespace = "")
        int myNum);

}
