
package com.javaproject.examplecollect.wsdlclient.airlinewsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DomesticAirlineSoap", targetNamespace = "http://WebXml.com.cn/")
public interface DomesticAirlineSoap {


    /**
     * <br /><h3>�������ڷɻ�����ʱ�̱�Web Services֧�ֵ�ȫ��������Ӣ�����ƺ���д DataSet</h3><p>����������ޣ��������ݣ��ṹΪ Item(enCityName)����Ӣ�����ơ�Item(cnCityName)�����������ơ�Item(Abbreviation)��д��������Ӣ��������������</p><br />
     * 
     * @return
     *     returns com.javaproject.examplecollect.wsdlclient.airlinewsdl.GetDomesticCityResponse.GetDomesticCityResult
     */
    @WebMethod(action = "http://WebXml.com.cn/getDomesticCity")
    @WebResult(name = "getDomesticCityResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getDomesticCity", targetNamespace = "http://WebXml.com.cn/", className = "com.javaproject.examplecollect.wsdlclient.airlinewsdl.GetDomesticCity")
    @ResponseWrapper(localName = "getDomesticCityResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.javaproject.examplecollect.wsdlclient.airlinewsdl.GetDomesticCityResponse")
    public com.javaproject.examplecollect.wsdlclient.airlinewsdl.GetDomesticCityResponse.GetDomesticCityResult getDomesticCity();

    /**
     * <br /><h3>��ú���ʱ�̱� DataSet</h3><p>���������startCity = �������У����ĳ������ƻ���д������Ĭ�ϣ��Ϻ�����lastCity = �ִ���У����ĳ������ƻ���д������Ĭ�ϣ���������theDate = �������ڣ�String ��ʽ��yyyy-MM-dd���磺2007-07-02������Ĭ�ϵ��죩��userID = ��ҵ�û�ID������û�����Ҫ��<br />�������ݣ�DataSet��Table(0)�ṹΪ Item(Company)���չ�˾��Item(AirlineCode)����š�Item(StartDrome)����������Item(ArriveDrome)���������Item(StartTime)����ʱ�䡢Item(ArriveTime)����ʱ�䡢Item(Mode)���͡�Item(AirlineStop)��ͣ��Item(Week)�������ڣ����ڣ�</p><br />
     * 
     * @param startCity
     * @param theDate
     * @param lastCity
     * @param userID
     * @return
     *     returns com.javaproject.examplecollect.wsdlclient.airlinewsdl.GetDomesticAirlinesTimeResponse.GetDomesticAirlinesTimeResult
     */
    @WebMethod(action = "http://WebXml.com.cn/getDomesticAirlinesTime")
    @WebResult(name = "getDomesticAirlinesTimeResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getDomesticAirlinesTime", targetNamespace = "http://WebXml.com.cn/", className = "com.javaproject.examplecollect.wsdlclient.airlinewsdl.GetDomesticAirlinesTime")
    @ResponseWrapper(localName = "getDomesticAirlinesTimeResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.javaproject.examplecollect.wsdlclient.airlinewsdl.GetDomesticAirlinesTimeResponse")
    public com.javaproject.examplecollect.wsdlclient.airlinewsdl.GetDomesticAirlinesTimeResponse.GetDomesticAirlinesTimeResult getDomesticAirlinesTime(
        @WebParam(name = "startCity", targetNamespace = "http://WebXml.com.cn/")
        String startCity,
        @WebParam(name = "lastCity", targetNamespace = "http://WebXml.com.cn/")
        String lastCity,
        @WebParam(name = "theDate", targetNamespace = "http://WebXml.com.cn/")
        String theDate,
        @WebParam(name = "userID", targetNamespace = "http://WebXml.com.cn/")
        String userID);

}
